
ingress:
  name: airflow-ingress
  host: airflow-test.asset-forome-dev-162fa491ef10b14d22843708d94ef0ba-0000.us-south.containers.appdomain.cloud
  certificate: asset-forome-dev-162fa491ef10b14d22843708d94ef0ba-0000 

airflow:
  name: cwl-airflow
  project: cwl-airflow
  image:
    repository: https://github.com/nikita-kapishev/cwl-airflow-openshift.git
    git_branch: master
  output_registry: image-registry.openshift-image-registry.svc:5000
  buildArgs:
    AIRFLOW_CONDA_ENV: "conda_default"
    POSTGRE_SERVER: "postgresql"
    POSTGRE_DB: "airflow"
    POSTGRE_USER: "airflow"
    POSTGRE_PASS: "airflow"
  env:
    AIRFLOW_CONDA_ENV: "conda_default"
    POSTGRE_SERVER: "postgresql"
    WEB_SERVER_PORT: "8080"
    AIRFLOW_HOME: "/opt/airflow"
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow:@postgres/airflow"
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW_CONN_METADATA_DB: "postgresql+psycopg2://airflow:airflow:@postgres/airflow"
    AIRFLOW_VAR__METADATA_DB_SCHEMA: "airflow"
    AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: "10"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
    _AIRFLOW_DB_UPGRADE: "True"
    _AIRFLOW_WWW_USER_CREATE: "True"
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    _AIRFLOW_WWW_USER_USERNAME: "airflow"
    _AIRFLOW_WWW_USER_PASSWORD: "airflow"
    AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080"
    AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs"
    PROJECT_DIR: "/opt/airflow/project"