apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.airflow.name }}-scheduler
  labels:
    app: {{ .Values.airflow.name }}-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.airflow.name }}-scheduler
  template:
    metadata:
      labels:
        app: {{ .Values.airflow.name }}-scheduler
    spec:
      containers: 
        - name: {{ .Values.airflow.name }}-scheduler
          image: "{{ .Values.airflow.output_registry }}/{{ .Values.airflow.project }}/{{ .Values.airflow.name }}"
          imagePullPolicy: IfNotPresent
        {{- if .Values.airflow.env }}
          env:
          {{- range $key, $val := .Values.airflow.env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
          {{- end }}
        {{- end }}
          # terminationMessagePath: /dev/termination-log
          # terminationMessagePolicy: File
          tty: true
          stdin: true
          # command: [ "bash" ]
          # args: [ "-c" ,"tail -f /dev/null" ]
          command: [ "entrypoint.sh" ]
          args: [ "airflow" ,"scheduler" ]
