apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.airflow.name }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.airflow.git_uri }}
      ref: {{ .Values.airflow.git_branch }}
    type: Docker
  strategy:
    dockerStrategy: 
      noCache: false
      dockerfilePath: Dockerfile
      buildArgs:
        - name: "AIRFLOW_CONDA_ENV"
          value: "conda_default"
  output:
    to:
      kind: ImageStreamTag
      name: "{{ .Values.airflow.name }}:latest"
