apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.airflow.name }}
  labels:
    app: {{ .Values.airflow.name }}
spec:
  to:
    kind: Service
    name: {{ .Values.airflow.name }}
    weight: 100
  port:
    targetPort: {{ .Values.airflow.name }}
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  wildcardPolicy: None