apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.airflow.name }}
  labels:
    app: {{ .Values.airflow.name }}
spec:
  ports:
  - name: {{ .Values.airflow.name }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.airflow.name }}
  sessionAffinity: None
  type: ClusterIP