kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-claim
  namespace: {{ .Values.airflow.project }}
  labels:
    app: {{ .Values.airflow.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: ibmc-vpc-block-10iops-tier